// AUTO-GENERATED — do not edit manually
// Generated by packages/scripts/generate-segment-mapping.mjs at 2026-08-15
// Source: 12 blog articles from apps/blog/content/en/ + apps/blog/content/zh/

/**
 * Blog article slug → Chinese display name mapping.
 * Used by the dashboard pathToBreadcrumb() to display Chinese path labels
 * without requiring manual SEGMENT_LABELS entries.
 */
export const BLOG_SEGMENT_LABELS: Record<string, string> = {
  'ccc-certification-explained': `海外品牌必读的 CCC 认证全攻略`,
  'china-import-compliance-guide': `如何判断您的产品适用哪些中国进口法规`,
  'china-label-compliance': `中国标签合规的十大常见错误`,
  'china-trademark-registration': `中国商标先申请制度 越早注册越安全`,
  'cosmetics-nmpa-filing': `国际品牌化妆品入华 NMPA 备案指南`,
  'cross-border-ecommerce-china': `跨境电商进入中国 先了解这些监管要求`,
  'gacc-decree-280': `海关总署 280 号令 GACC 注册新规解读`,
  'gacc-registration-guide': `食品出口商必读 海关总署注册完整指南`,
  'health-supplements-china-import-route': `保健食品入华路线怎么选 GACC、蓝帽还是跨境`,
  'korean-cosmetics-china-guide': `韩国化妆品入华 NMPA 备案与分类指南`,
  'medical-device-import-license': `中国医疗器械进口许可与 NMPA 注册指南`,
  'pet-food-brand-gacc-registration': `美国宠物食品品牌进军中国市场的实战复盘`,
};

/**
 * Blog article slug → English display name mapping (for English locale).
 */
export const BLOG_SEGMENT_LABELS_EN: Record<string, string> = {
  'ccc-certification-explained': `China CCC Mark Requirements Every Foreign Brand Should Know`,
  'china-import-compliance-guide': `Which China Import Regulations Apply to Your Product`,
  'china-label-compliance': `10 Common Mistakes in China Label Compliance`,
  'china-trademark-registration': `The First to File Advantage in China Trademark Registration`,
  'cosmetics-nmpa-filing': `NMPA Cosmetics Filing Guide for International Brands`,
  'cross-border-ecommerce-china': `A Regulatory Guide to Cross Border Ecommerce in China`,
  'gacc-decree-280': `GACC Registration Under China's New Decree 280`,
  'gacc-registration-guide': `Complete Guide to GACC Registration for Food Exporters`,
  'health-supplements-china-import-route': `GACC, NMPA and CBEC Routes for China Health Supplements`,
  'korean-cosmetics-china-guide': `NMPA Filing and Import Guide for Korean Cosmetics in China`,
  'medical-device-import-license': `China Medical Device Import License & NMPA Registration`,
  'pet-food-brand-gacc-registration': `How a US Pet Food Brand Entered the Chinese Market`,
};
