// AUTO-GENERATED — do not edit manually
// Generated by packages/scripts/generate-segment-mapping.mjs at 2026-07-29
// Source: 9 blog articles from apps/blog/content/en/ + apps/blog/content/zh/

/**
 * Blog article slug → Chinese display name mapping.
 * Used by the dashboard pathToBreadcrumb() to display Chinese path labels
 * without requiring manual SEGMENT_LABELS entries.
 */
export const BLOG_SEGMENT_LABELS: Record<string, string> = {
  'ccc-certification-explained': `CCC认证 国外品牌需要知道什么`,
  'china-import-compliance-guide': `中国进口合规性 哪些法规适用于您的产品？`,
  'china-label-compliance': `中国标签合规性 10 个常见错误`,
  'china-trademark-registration': `中国商标注册 先发优势`,
  'cosmetics-nmpa-filing': `NMPA化妆品备案 国际品牌指南`,
  'cross-border-ecommerce-china': `中国跨境电子商务 监管清单`,
  'gacc-registration-guide': `GACC 食品出口商注册完整指南`,
  'health-supplements-china-import-route': `中国的保健品和功能食品 GACC、NMPA 还是跨境 选择正确的路线`,
  'korean-cosmetics-china-guide': `韩国化妆品在中国 NMPA备案、头皮护理分类及进口指南`,
};

/**
 * Blog article slug → English display name mapping (for English locale).
 */
export const BLOG_SEGMENT_LABELS_EN: Record<string, string> = {
  'ccc-certification-explained': `What Foreign Brands Need to Know About CCC Certification`,
  'china-import-compliance-guide': `Which China Import Regulations Apply to Your Product`,
  'china-label-compliance': `10 Common Mistakes in China Label Compliance`,
  'china-trademark-registration': `The First to File Advantage in China Trademark Registration`,
  'cosmetics-nmpa-filing': `NMPA Cosmetics Filing Guide for International Brands`,
  'cross-border-ecommerce-china': `A Regulatory Guide to Cross Border Ecommerce in China`,
  'gacc-registration-guide': `Complete Guide to GACC Registration for Food Exporters`,
  'health-supplements-china-import-route': `GACC, NMPA and Cross Border Routes for Health Supplements in China`,
  'korean-cosmetics-china-guide': `NMPA Filing and Import Guide for Korean Cosmetics in China`,
};
